# -------------------------- #
#          USER ROLES        #
# -------------------------- #

## The available user roles for users in a Stitch account.

- "general-user"
- "sso-admin"
- "invoice-admin"